# Generated by Django 5.0.7 on 2024-10-16 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='image_id',
            field=models.ForeignKey(blank=True, default=123, on_delete=django.db.models.deletion.CASCADE, to='site_back.image', verbose_name='img_id'),
            preserve_default=False,
        ),
    ]
