# Generated by Django 5.0.7 on 2024-10-18 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_back', '0003_alter_polygon_image_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('url',)},
        ),
        migrations.AlterUniqueTogether(
            name='polygon',
            unique_together={('user_id', 'polygon_id', 'polygon_data')},
        ),
        migrations.AddField(
            model_name='image',
            name='polygon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='site_back.polygon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='polygon',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.RemoveField(
            model_name='polygon',
            name='image_id',
        ),
    ]
