# Generated by Django 5.0.7 on 2024-10-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_back', '0004_alter_image_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polygon',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='polygon',
            unique_together=set(),
        ),
    ]
