# Generated by Django 5.0.7 on 2024-10-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_back', '0005_rename_user_id_polygon_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='user',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='polygon',
            old_name='user',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='sessionstorage',
            old_name='user',
            new_name='login',
        ),
    ]
